version: 2
jobs:
  build:
    working_directory: ~/glasser/vote.davidglasser.net
    docker:
    - image: cimg/base:current
    steps:
    - checkout
    - run: |
        curl https://mise.run | sh
        mise install
    - run: mise x -- hugo -v
    - run: '[ "$CIRCLE_BRANCH" == master ] && mise x -- s3deploy -source=public/ -region=us-east-1 -bucket=vote.davidglasser.net -public-access || true'
