version: 2
jobs:
  build:
    working_directory: ~/glasser/vote.davidglasser.net
    docker:
    - image: circleci/buildpack-deps:latest
    steps:
    - checkout
    - run: curl https://mise.run | sh
    - run: curl mise install
    - run: bash ./ci-install-deps.sh
    - run: mise x -- hugo -v
    - run: '[ "$CIRCLE_BRANCH" == master ] && ./s3deploy -source=public/ -region=us-east-1 -bucket=vote.davidglasser.net -public-access || true'
