name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true  # for ubi backend
      - run: hugo -v
      - run: s3deploy -source=public/ -region=us-east-1 -bucket=vote.davidglasser.net -public-access
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: aws cloudfront create-invalidation --distribution-id=${{ secrets.CF_DISTRIBUTION_ID }} --paths='/*'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # https://github.com/aws/aws-cli/issues/5262#issuecomment-705832151
          AWS_EC2_METADATA_DISABLED: 'true'
